const fruits = ["Banana", "Orange", "Apple", "Mango"];
console.log(`Before Splice method-${fruits }`);
const deletedElements =fruits.splice(2, 0, "Lemon", "Kiwi");
console.log(`After Splice Method -${ fruits}`);
console.log(`Removed Elemnts -${deletedElements}`);
console.log('.....................2 example....................................');
const number = [10,20,40,50,60];
console.log(`Before Splice method-${number}`);
const DeletedElements =number.splice(1, 2,130,190);
console.log(`After Splice Method -${ number }`);
console.log(`Removed Elemnts -${DeletedElements}`);
console.log('.....................3 example....................................');
const city = ['Anantapur','Banglore','Hyderabad','chennai','Delhi'];
console.log(`Before Splice method-${city}`);
const RemovedElements =city.splice(0, 2);
console.log(`After Splice Method -${ city}`);
console.log(`Removed Elemnts -${RemovedElements}`);
console.log('.....................4 example....................................');
const numbers = [10,20,40,50,60];
console.log(`Before Splice method-${numbers}`);
const Elements =number.splice(3, 1,130,190);
console.log(`After Splice Method -${ numbers }`);
console.log(`Removed Elemnts -${Elements}`);
console.log('.....................5 example....................................');
const fruit = ["Banana", "Orange", "Apple", "Mango"];
console.log(`Before Splice method-${fruit }`);
const deleted =fruit.splice(2,2);
console.log(`After Splice Method -${ fruit}`);
console.log(`Removed Elemnts -${deleted}`);

